#!/usr/bin/env node
/**
 * Convert NWEA 2025 norms CSV matrix into a JS module.
 *
 * Input:  norms_2025_matrix.csv — 99 rows (percentiles 1–99) × N columns
 * Output: src/utils/normsData.js — exported object keyed by column name,
 *         each value an array of 99 RIT scores (index 0 = percentile 1).
 *
 * Run: node scripts/convert-norms.js
 */

import fs from 'fs';
import path from 'path';
import { parse } from 'csv-parse/sync';

const INPUT_CSV = path.resolve(
  import.meta.dirname,
  '../../student_progress_animation/norms_tables/csv/norms_2025_matrix.csv'
);
const OUTPUT_JS = path.resolve(import.meta.dirname, '../src/utils/normsData.js');

const csv = fs.readFileSync(INPUT_CSV, 'utf-8');
const rows = parse(csv, { columns: true, skip_empty_lines: true });

// rows is an array of objects keyed by header name
// First column is "Percentile", rest are like "Math_Fal_GK", "Math_Win_G7", etc.
const columns = Object.keys(rows[0]).filter(k => k !== 'Percentile');

const norms = {};
for (const col of columns) {
  norms[col] = rows.map(row => parseInt(row[col], 10));
}

// Validate: every column should have exactly 99 entries (percentiles 1-99)
for (const [col, values] of Object.entries(norms)) {
  if (values.length !== 99) {
    console.error(`ERROR: ${col} has ${values.length} entries, expected 99`);
    process.exit(1);
  }
  if (values.some(v => isNaN(v))) {
    console.error(`ERROR: ${col} has NaN values`);
    process.exit(1);
  }
}

// Generate compact JS output
const entries = Object.entries(norms)
  .map(([key, values]) => `  "${key}": [${values.join(',')}]`)
  .join(',\n');

const output = `// Auto-generated by scripts/convert-norms.js — do not edit manually
// NWEA 2025 norms: column key → array of 99 RIT scores (index 0 = percentile 1, index 98 = percentile 99)
export const NORMS_2025 = {
${entries}
};
`;

fs.writeFileSync(OUTPUT_JS, output);
console.log(`Wrote ${columns.length} columns to ${OUTPUT_JS} (${(output.length / 1024).toFixed(1)} KB)`);
